import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Theme from './Components/Theme/Theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Landing',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body style={{ margin: '0px' }} className={inter.className}>
				<Theme>{children}</Theme>
			</body>
		</html>
	)
}
